//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OynaKazan.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EarnPointHistory
    {
        public int Id { get; set; }
        public int User_Id { get; set; }
        public int Puan { get; set; }
        public System.DateTime Tarih { get; set; }
    }
}
