//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OynaKazan.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OynaKazanEntities : DbContext
    {
        public OynaKazanEntities()
            : base("name=OynaKazanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<BankAccounts> BankAccounts { get; set; }
        public virtual DbSet<Bans> Bans { get; set; }
        public virtual DbSet<EarnPointHistory> EarnPointHistory { get; set; }
        public virtual DbSet<ExchangePoints> ExchangePoints { get; set; }
        public virtual DbSet<ExPointHistory> ExPointHistory { get; set; }
        public virtual DbSet<Iletisim> Iletisim { get; set; }
        public virtual DbSet<PayRequests> PayRequests { get; set; }
        public virtual DbSet<SupportMessages> SupportMessages { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserDetails> UserDetails { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
