//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OynaKazan.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetails
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public decimal Bakiye { get; set; }
        public int Puan { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
